var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/project/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__eeb96741._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_b54ca67a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ad8c091._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ec08af90._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_project_page_actions_2e17deae.js")
R.m(52991)
module.exports=R.m(52991).exports
