var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/project/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__47b456ba._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_e1c18b5e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ad8c091._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ec08af90._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_project_[id]_page_actions_d20b4a2c.js")
R.m(47682)
module.exports=R.m(47682).exports
